**Numpy**

In [ ]:
import numpy as np

In [ ]:
# numpy array olustur
# liste = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]
dizi = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])
dizi

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [ ]:
# array boyutu
dizi.shape # (15,) -> 15x1 lik bir vektor

(15,)

In [ ]:
# 15x1 lik bir arrayi 3x5 lik bir matrise cevirelim
dizi2 = dizi.reshape(3,5)
dizi2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [ ]:
print("shape: ", dizi2.shape)
print("dimension: ", dizi2.ndim)
print("size: ",dizi2.size)
print("type: ", type(dizi2))

shape:  (3, 5)
dimension:  2
size:  15
type:  <class 'numpy.ndarray'>


In [ ]:
dizi2D = np.array([[1,2,3,4],[5,6,7,8],[9,8,7,5]])
dizi2D

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 8, 7, 5]])

In [ ]:
# sifirlardan olusan bir array olusturalim
sifir_dizi = np.zeros((3,4))
sifir_dizi

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
# birlerden olsan array
bir_dizi = np.ones((3,4))
bir_dizi

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
# bos bir array olustur
bos_dizi = np.empty((2,4))
bos_dizi

array([[5.04540792e-310, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000]])

In [ ]:
# arange(x,y,basamak) x den baslar y ye (y dahil degil) kadar gider basamak buyuklugunder artarak ilerler
# 10, 50, basamak = 5
dizi_aralik = np.arange(10,50,8)
dizi_aralik

array([10, 18, 26, 34, 42])

In [ ]:
# linspace  (x,y,basamak) x ve y(dahil) araliginde basamak kadar sayiya boler
dizi_bosluk = np.linspace(10,50,103)
len(dizi_bosluk)

103

**Numpy Temel Operasyonları**

In [ ]:
import numpy as np

In [ ]:
a = np.array([1,2,3])
b = np.array([4,5,6])

In [ ]:
print("Toplama: ", a+b)
print("Cikarma: ", a-b)
print("Dizinin kendisi ile carpimi: ", a**2)

Toplama:  [5 7 9]
Cikarma:  [-3 -3 -3]
Dizinin kendisi ile carpimi:  [1 4 9]


In [ ]:
# filtreleme
a = np.array([1,2,3])
filtre = a < 2 # a array'nin icerisinde bulunan 2 den kucuk degerleri goster
filtre

array([ True, False, False])

In [ ]:
# matris carpimi
a = np.array([1,2,3])
b = np.array([4,5,6])
a.dot(b)

32

In [ ]:
a = np.array([[1,2,3],[4,5,6]]) # 2x3
b = np.array([[4,5,6],[1,2,3]]) # 2x3 ->T-> 3x2
a.dot(b.T)

array([[32, 14],
       [77, 32]])

In [ ]:
a = np.array([[1,2,3],
              [4,5,6]])
print(sum(a))
print(np.sum(a))

[5 7 9]
21


In [ ]:
print(a.max())
print(np.max(a))

6
6


In [ ]:
print(a.min())
print(np.min(a))

1
1


In [ ]:
# satir satir toplama
a.sum(axis = 1)

array([ 6, 15])

In [ ]:
# sutun sutun toplama
a.sum(axis = 0)

array([5, 7, 9])

In [ ]:
# kare koku
np.sqrt(a)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [ ]:
# karesi
print(np.square(a))
print(a**2)

[[ 1  4  9]
 [16 25 36]]
[[ 1  4  9]
 [16 25 36]]


In [ ]:
# np.random.rand(3,3)

array([[0.58340416, 0.36154522, 0.08008394],
       [0.99149938, 0.18092345, 0.25359485],
       [0.06613093, 0.11380878, 0.88067948]])

In [ ]:
# rastgele sayi uretme
rastgele_dizi = np.random.random((3,3)) # normal dagilima gore 0-1
rastgele_dizi

array([[0.23809254, 0.58125061, 0.02652949],
       [0.56337976, 0.67939152, 0.79925741],
       [0.7477823 , 0.36735526, 0.94165395]])

In [ ]:
rastgele_dizi = np.random.normal(0 ,1 , (5,3)) # normal dagilima 0 ortalamali 1 std, 5 adet deger uret
rastgele_dizi

array([[ 0.88000137, -0.24306213, -1.76753099],
       [ 1.28405075, -0.16232154, -0.65840633],
       [ 0.36765998,  0.04215824, -0.5232443 ],
       [ 0.77148143, -0.03513502,  1.62264967],
       [ 1.50764868,  0.32115817,  0.930468  ]])

**indeksleme ve slicing**

In [ ]:
import numpy as np

In [ ]:
dizi= np.array([1,2,3,4,5,6,7])
dizi[3]

4

In [ ]:
dizi[0:4]

array([1, 2, 3, 4])

In [ ]:
dizi[:4]

array([1, 2, 3, 4])

In [ ]:
dizi[::-1]

array([7, 6, 5, 4, 3, 2, 1])

In [ ]:
dizi2D = np.array([[1,2,3,4,5],[6,7,8,9,10]])
dizi2D

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [ ]:
dizi2D[1,2]

8

In [ ]:
dizi2D[1, :] # : = hepsi sutun kismina yazdigim icin tum sutunlar demek

array([ 6,  7,  8,  9, 10])

In [ ]:
dizi2D[:, 2] #  : = hepsi satir kismina yazdigim icin tum satirlar demek

array([3, 8])

In [ ]:
dizi2D[ 0, 0:2] # 1,  2

array([1, 2])

In [ ]:
dizi2D[:, 2:4]
"""
[ 1,  2,  3,  4,  5],
[ 6,  7,  8,  9, 10]
"""


array([[3, 4],
       [8, 9]])

In [ ]:
dizi2D[-1, :]

array([ 6,  7,  8,  9, 10])

In [ ]:
dizi2D[[0,1], [1,3]]

array([2, 9])

**shape manipulation**

In [ ]:
import numpy as np

In [ ]:
dizi2D = np.array([[1,2,3],[4,5,6],[7,8,9]])
dizi2D

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
dizi2D_shape = dizi2D.shape
dizi2D_shape

(3, 3)

In [ ]:
dizi2D.reshape(dizi2D_shape[0]*dizi2D_shape[1],1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [ ]:
dizi2D.reshape(dizi2D_shape[0]*dizi2D_shape[1],-1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [ ]:
dizi2D.ravel() # tensorflow -> flatten

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
dizi2D.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [ ]:
dizi2D=np.array([[1,2,3],[4,5,6],[7,8,9]])
dizi2D.shape

(3, 3)

In [ ]:
dizi2D_shape=dizi2D.shape
dizi2D_shape

(3, 3)

In [ ]:
print(dizi2D.reshape(dizi2D_shape[0]*dizi2D_shape[1],-1))

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


In [ ]:
""""
[[1,2]
[3,4]]

reshape(4,-1)

[1,2,3,4]
"""

In [ ]:
"""
1) A array = 2 boyutlu bir tane array -> (3,5)
2) B array = 1 boyutlu bir tane array -> (15,)
3) B array'ini (3,5) olacak sekilde reshape yapalim
4) C = A + B
5) D=linspace ve E=arange ile (3,5) lik matrisler olusturalim.
6) F = D + E
7) C'nin ve F'nin her bir elemanini for dongusu ile eleman eleman carpip G = (15,1) boyutunda elde edelim.
8) C ve F'yi (15,1) sonrasında C'nin ilk elemani ile F'nin son elemani toplayarak ilerleyelim.
9) toplam degerleri eger 1 den buyukse G1 isimli bir listeye atalim, else ise G2 isimli listeye atalim
"""
import numpy as np
# 2 boyutlu bir dizi oluşturma (3x5)
A = np.random.rand(3, 5)  # 0 ile 1 arasında rastgele sayılarla dolu 3x5'lik bir dizi
# 1 boyutlu bir dizi oluşturma (15 elemanlı)
B = np.arange(15)  # 0'dan 14'e kadar sayıları içeren bir dizi
# B dizisini 3x5 boyutunda yeniden şekillendirme
B = B.reshape(3, 5)
# A ve B dizilerini toplama
C = A + B
print("C: ",C)
D=np.linspace(10,50,15).reshape(3,5)
print("D: ",D)
E=np.arange(10,160,10).reshape(3,5)
print("E: ",E)
F=D+E
print("F: ",F)
G = []
for i in range(C.shape[0]):  # 3
    for j in range(C.shape[1]):  # 5
        G.append(C[i, j] * F[i, j])
print("G shape: ",np.array(G).shape)

C:  [[ 0.32742418  1.39065597  2.83093282  3.62819265  4.7901782 ]
 [ 5.46543483  6.64074862  7.93781858  8.61639906  9.56028326]
 [10.43240607 11.86031746 12.67615277 13.28471227 14.3735089 ]]
D:  [[10.         12.85714286 15.71428571 18.57142857 21.42857143]
 [24.28571429 27.14285714 30.         32.85714286 35.71428571]
 [38.57142857 41.42857143 44.28571429 47.14285714 50.        ]]
E:  [[ 10  20  30  40  50]
 [ 60  70  80  90 100]
 [110 120 130 140 150]]
F:  [[ 20.          32.85714286  45.71428571  58.57142857  71.42857143]
 [ 84.28571429  97.14285714 110.         122.85714286 135.71428571]
 [148.57142857 161.42857143 174.28571429 187.14285714 200.        ]]
G shape:  (15,)


In [ ]:
"""
[1,2,3]

[4,5,6]
7,7,7
"""
C = C.reshape(15,1)
F = F.reshape(15,1)
F =F[::-1]
G1 = []
G2 = []
for i in range(len(C)):
    toplam = C[i] + F[i]
    if toplam > 1:
        G1.append(toplam)
    else:
        G2.append(toplam)
print(G1,G2)

[array([20.32742418]), array([34.24779882]), array([48.54521854]), array([62.19962122]), array([76.21874962]), array([89.75114912]), array([103.78360576]), array([117.93781858]), array([131.47354192]), array([145.27456898]), array([159.00383464]), array([173.28888889]), array([186.96186706]), array([200.42756941]), array([214.3735089])] []


In [ ]:
C_flat = C.reshape(-1, 1)  # -1 otomatik olarak 15 elemanı kullanır
F_flat = F.reshape(-1, 1)

# G1 ve G2 listelerini tanımlama
G1 = []
G2 = []

# C'nin ilk elemanı ve F'nin son elemanı toplama işlemi ile ilerleme
for i in range(len(C_flat)):  # C_flat'in uzunluğunu kullanarak döngüyü oluştur
    toplam = C_flat[i, 0] + F_flat[len(F_flat) - 1 - i, 0]  # len kullanarak sondan eleman al
    if toplam > 1:
        G1.append(toplam)
    else:
        G2.append(toplam)
# Sonuçları yazdırma
print("G1 (Toplam > 1 olanlar):", G1)
print("G2 (Toplam <= 1 olanlar):", G2)

G1 (Toplam > 1 olanlar): [200.3274241810467, 188.53351310915698, 177.11664710813443, 165.05676407668426, 153.36160676686742, 141.17972054778826, 129.4978914723449, 117.93781858145316, 105.75925620685932, 93.84599755056932, 81.86097749537447, 70.43174603218262, 58.39043848529876, 46.14185512387553, 34.37350889945884]
G2 (Toplam <= 1 olanlar): []


 **Stacking**

In [ ]:
import numpy as np

In [ ]:
dizi1 = np.array([[1,2], [3,4]])
dizi1

array([[1, 2],
       [3, 4]])

In [ ]:
dizi2 = np.array([[-1,-2], [-3,-4]])
dizi2

array([[-1, -2],
       [-3, -4]])

In [ ]:
dizi_dikey = np.vstack((dizi1, dizi2))
dizi_dikey

array([[ 1,  2],
       [ 3,  4],
       [-1, -2],
       [-3, -4]])

In [ ]:
dizi_yatay = np.hstack((dizi1, dizi2))
dizi_yatay

array([[ 1,  2, -1, -2],
       [ 3,  4, -3, -4]])

In [ ]:
# problem tanimi: 2 boyutlu (2 satir ve 2 sutun) 3 adet array olustur,
# bunlari yatayda ve dikeyde birlestir
np.hstack((dizi1, dizi1, dizi1))

array([[1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4]])

In [ ]:
np.vstack((dizi1, dizi1, dizi1))

array([[1, 2],
       [3, 4],
       [1, 2],
       [3, 4],
       [1, 2],
       [3, 4]])